### ISSUE TITLE
Use in conjunction with Breeze?

### ISSUE THREAD

**Issue by joshstobbs** [laravel-presets/inertia#7]
Hey there, this might be a simple question but would there be any issues if I installed Breeze and then added this preset on top of that?

I know that the preset calls for a default Laravel installation, but I had this thought as it might save a fair bit of time.

Thanks so much!

**Comment by innocenzi** [comment]
Hey, yes, Breeze uses the convention where you use the `js` directory, with `Components`, `Pages` etc - this preset erases `js` and uses `views` directly (it follows conventions closer to what you would do with a standalone Vue app).

Unfortunately this preset isn't very compatible with Breeze, but you can still manually copy the `js` files and put them back.

**Comment by joshstobbs** [comment]
Awesome, thank you for that.  Kind of what I assumed, thanks so much!
